class Global_Vars:
    model = []
    UNET_PATH = []
    Images = []
    Data = []
    Target = []
    learnperc = None
    Train_Data = []
    Train_Target = []
    Test_Data = []
    Test_Target = []
    wave_Feat = []
    temp_Feat = []
    spact_Feat = []
    spat_Feat = []
    auto_Feat = []
